# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AviationPipe' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'RosaKit'
  pod 'TensorFlowLiteSwift'


  # Pods for AviationPipe

  target 'AviationPipeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AviationPipeUITests' do
    # Pods for testing
  end

end
